
# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Archives: /archives

# stylesheets loaded in the <head>
stylesheets:
- /css/th.css

# scripts loaded in the end of the body
scripts:
- /js/th.js

search_tags: ['Hexo', 'JavaScript', 'Botanical', 'Vocational', 'Cycling', 'Language']